services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: reponest-web:local
    pull_policy: build

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: reponest-api:local
    pull_policy: build
