name: Publish container

on:
  push:
    branches: [main]
    tags: ["v*"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      output: image
      push: true
      context: .
      file: ./Dockerfile
      platforms: linux/amd64,linux/arm64
      cache: true
      cache-mode: max
      cache-scope: reponest
      sbom: true
      set-meta-labels: true
      set-meta-annotations: true
      meta-images: ghcr.io/elainaicey/reponest
      meta-tags: |
        type=raw,value=latest,enable={{is_default_branch}}
        type=ref,event=tag
        type=semver,pattern={{version}}
        type=sha,prefix=sha-
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
